version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    hostname: jenkinshost
    ports:
      - '${JENKINS_HTTP_PORT}:8080'
      - '${JENKINS_HTTPS_PORT}:8443'
      - '${JENKINS_JAVA_API_PORT}:50000'
    volumes:
      - ${VAR_HOME}/jenkins:/var/jenkins_home
      # mount docker sock and binary for docker in docker (only works on linux)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
